# Домашнее задание № 2. Мешок слов

## Задание 1 (3 балла)

У векторайзеров в sklearn есть встроенная токенизация на регулярных выражениях. Найдите способо заменить её на кастомную токенизацию

Обучите векторайзер с дефолтной токенизацией и с токенизацией razdel.tokenize. Обучите классификатор (любой) с каждым из векторизаторов. Сравните метрики и выберете победителя. 

(в вашей тетрадке должен быть код обучения и все метрики; если вы сдаете в .py файлах то сохраните полученные метрики в отдельном файле или в комментариях)

In [568]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.metrics.pairwise import cosine_distances, cosine_similarity
from razdel import tokenize

from IPython.display import Image
from IPython.core.display import HTML

In [569]:
data = pd.read_csv('labeled.csv')
data.toxic.value_counts(normalize=True)

toxic
0.0    0.66514
1.0    0.33486
Name: proportion, dtype: float64

In [570]:
data.head()

comment  toxic
0               Верблюдов-то за что? Дебилы, бл...\n    1.0
1  Хохлы, это отдушина затюканого россиянина, мол...    1.0
2                          Собаке - собачья смерть\n    1.0
3  Страницу обнови, дебил. Это тоже не оскорблени...    1.0
4  тебя не убедил 6-страничный пдф в том, что Скр...    1.0

In [571]:
def razdel_tokenize(text):
    tokens = list(tokenize(text))
    return [_.text for _ in tokens]

In [572]:
vectorizer_def = TfidfVectorizer(min_df=10, max_df=0.3)
vectorizer_raz = TfidfVectorizer(min_df=10, max_df=0.3, tokenizer=razdel_tokenize)

In [573]:
train, test = train_test_split(data, test_size=0.1, shuffle=True)
train.reset_index(inplace=True)
test.reset_index(inplace=True)

In [574]:
default_X = vectorizer_def.fit_transform(train.comment)
default_X_test = vectorizer_def.transform(test.comment)

razdel_X = vectorizer_raz.fit_transform(train.comment)
razdel_X_test = vectorizer_raz.transform(test.comment)

C:\Users\robst\PycharmProjects\HSE_NLP\venv\Lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [575]:
default_X.shape, default_X_test.shape

((12970, 3373), (1442, 3373))

In [576]:
razdel_X.shape, razdel_X_test.shape

((12970, 3438), (1442, 3438))

In [577]:
y = train.toxic.values
y_test = test.toxic.values

In [578]:
clf_def = LogisticRegression(C=0.1, class_weight='balanced')
clf_raz = LogisticRegression(C=0.1, class_weight='balanced')

In [579]:
clf_def.fit(default_X, y)

LogisticRegression(C=0.1, class_weight='balanced')

In [580]:
clf_raz.fit(razdel_X, y)

LogisticRegression(C=0.1, class_weight='balanced')

In [581]:
preds_def = clf_def.predict(default_X_test)

In [582]:
preds_raz = clf_raz.predict(razdel_X_test)

In [583]:
preds_def

array([1., 1., 0., ..., 0., 0., 1.])

In [584]:
preds_raz

array([1., 1., 0., ..., 0., 0., 1.])

In [585]:
print(classification_report(y_test, preds_def, zero_division=0))

              precision    recall  f1-score   support

         0.0       0.88      0.84      0.86       983
         1.0       0.69      0.76      0.72       459

    accuracy                           0.82      1442
   macro avg       0.79      0.80      0.79      1442
weighted avg       0.82      0.82      0.82      1442



In [586]:
print(classification_report(y_test, preds_raz, zero_division=0))

              precision    recall  f1-score   support

         0.0       0.88      0.85      0.87       983
         1.0       0.71      0.76      0.73       459

    accuracy                           0.82      1442
   macro avg       0.80      0.81      0.80      1442
weighted avg       0.83      0.82      0.83      1442



In [587]:
probas_def = clf_def.predict_proba(default_X_test)
probas_raz = clf_raz.predict_proba(razdel_X_test)

In [588]:
probas_def

array([[0.05340328, 0.94659672],
       [0.30549029, 0.69450971],
       [0.67391072, 0.32608928],
       ...,
       [0.61579166, 0.38420834],
       [0.58468155, 0.41531845],
       [0.48555765, 0.51444235]])

In [589]:
probas_raz

array([[0.0539847 , 0.9460153 ],
       [0.29871491, 0.70128509],
       [0.67278682, 0.32721318],
       ...,
       [0.66314292, 0.33685708],
       [0.61673236, 0.38326764],
       [0.48408945, 0.51591055]])

In [590]:
preds_def = (probas_def[:,1]>0.85).astype(int)
preds_raz = (probas_raz[:,1]>0.85).astype(int)

In [591]:
print(classification_report(y_test, preds_def, zero_division=0))

              precision    recall  f1-score   support

         0.0       0.69      1.00      0.82       983
         1.0       0.93      0.06      0.11       459

    accuracy                           0.70      1442
   macro avg       0.81      0.53      0.47      1442
weighted avg       0.77      0.70      0.59      1442



In [592]:
print(classification_report(y_test, preds_raz, zero_division=0))

              precision    recall  f1-score   support

         0.0       0.70      1.00      0.82       983
         1.0       0.94      0.06      0.12       459

    accuracy                           0.70      1442
   macro avg       0.82      0.53      0.47      1442
weighted avg       0.77      0.70      0.60      1442



## Задание 2 (3 балла)

Преобразуйте таблицу с абсолютными частотностями в семинарской тетрадке в таблицу с tfidf значениями. (Таблица - https://i.ibb.co/r5Nc2HC/abs-bow.jpg) Формула tfidf есть в семинаре на картинке с пояснениями на английском.
Считать нужно в питоне. Формат итоговой таблицы может быть любым, главное, чтобы был код и можно было воспроизвести вычисления.

In [593]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import pandas as pd
from scipy.sparse.csr import csr_matrix

C:\Users\robst\AppData\Local\Temp\ipykernel_9584\3164112859.py:4: DeprecationWarning: Please use `csr_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csr` namespace is deprecated.
  from scipy.sparse.csr import csr_matrix


In [594]:
def razdel_tokenize_fix(text):
    tokens = list(tokenize(text))
    return [_.text for _ in tokens if _.text != ","]

In [595]:
vec = TfidfVectorizer(tokenizer=razdel_tokenize_fix)

In [596]:
texts = [
    "я и ты",
    "ты и я",
    "я, я и только я",
    "только не я",
    "он"
]

In [597]:
table = vec.fit_transform(texts)
print(table)

  (0, 4)	0.6778032959469461
  (0, 0)	0.5626379641131365
  (0, 5)	0.47330879280030447
  (1, 4)	0.6778032959469461
  (1, 0)	0.5626379641131365
  (1, 5)	0.47330879280030447
  (2, 3)	0.4056325249335055
  (2, 0)	0.33671163798017656
  (2, 5)	0.8497573345166112
  (3, 1)	0.7127752157729959
  (3, 3)	0.5750625560879445
  (3, 5)	0.4015651234424611
  (4, 2)	1.0


C:\Users\robst\PycharmProjects\HSE_NLP\venv\Lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


0 = sentence no.
4 = word index
0.6778032959469461 = tf-idf weight

In [598]:
for i, feature in enumerate(vec.get_feature_names_out()):
    print(i, feature)
feature_names = vec.get_feature_names_out()

0 и
1 не
2 он
3 только
4 ты
5 я


In [599]:
df = pd.DataFrame(table.toarray(), columns = vec.get_feature_names_out(), index=texts)
print(df)

                        и        не   он    только        ты         я
я и ты           0.562638  0.000000  0.0  0.000000  0.677803  0.473309
ты и я           0.562638  0.000000  0.0  0.000000  0.677803  0.473309
я, я и только я  0.336712  0.000000  0.0  0.405633  0.000000  0.849757
только не я      0.000000  0.712775  0.0  0.575063  0.000000  0.401565
он               0.000000  0.000000  1.0  0.000000  0.000000  0.000000


    ## Задание 3 (2 балла)

Обучите 2 любых разных классификатора из семинара. Предскажите токсичность для текстов из тестовой выборки (используйте одну и ту же выборку для обоих классификаторов) и найдите 10 самых токсичных для каждого из классификаторов. Сравните получаемые тексты - какие тексты совпадают, какие отличаются, правда ли тексты токсичные?

Требования к моделям:
а) один классификатор должен использовать CountVectorizer, другой TfidfVectorizer  
б) у векторазера должны быть вручную заданы как минимум 5 параметров (можно ставить разные параметры tfidfvectorizer и countvectorizer)  
в) у классификатора должно быть задано вручную как минимум 2 параметра (по возможности)  
г) f1 мера каждого из классификаторов должна быть минимум 0.75

*random_seed не считается за параметр

In [600]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from razdel import tokenize

In [601]:
def razdel_tokenize(text):
    tokens = list(tokenize(text))
    return [_.text for _ in tokens]

In [602]:
data = pd.read_csv('labeled.csv')
data.toxic.value_counts(normalize=True)

toxic
0.0    0.66514
1.0    0.33486
Name: proportion, dtype: float64

In [603]:
data.head()

comment  toxic
0               Верблюдов-то за что? Дебилы, бл...\n    1.0
1  Хохлы, это отдушина затюканого россиянина, мол...    1.0
2                          Собаке - собачья смерть\n    1.0
3  Страницу обнови, дебил. Это тоже не оскорблени...    1.0
4  тебя не убедил 6-страничный пдф в том, что Скр...    1.0

In [604]:
vec_count = CountVectorizer(min_df=8, max_df=0.3, tokenizer=razdel_tokenize, lowercase=True, ngram_range=(1,4), strip_accents='unicode')
vec_tfidf = TfidfVectorizer(min_df=8, max_df=0.3, tokenizer=razdel_tokenize, lowercase=True, ngram_range=(1,5), strip_accents='unicode')

In [605]:
train, test = train_test_split(data, test_size=0.1, shuffle=True)
train.reset_index(inplace=True)
test.reset_index(inplace=True)

In [606]:
count_X = vec_count.fit_transform(train.comment)
count_X_test = vec_count.transform(test.comment)

tfidf_X = vec_tfidf.fit_transform(train.comment)
tfidf_X_test = vec_tfidf.transform(test.comment)

C:\Users\robst\PycharmProjects\HSE_NLP\venv\Lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [607]:
count_X.shape, count_X_test.shape

((12970, 9234), (1442, 9234))

In [608]:
tfidf_X.shape, tfidf_X_test .shape

((12970, 9245), (1442, 9245))

In [609]:
y = train.toxic.values
y_test = test.toxic.values

In [610]:
dec_class = MultinomialNB(alpha=0.1)
dec_class.fit(count_X, y)
dec_preds = dec_class.predict(count_X_test)

print(classification_report(y_test, dec_preds))


              precision    recall  f1-score   support

         0.0       0.85      0.88      0.87       949
         1.0       0.76      0.71      0.73       493

    accuracy                           0.82      1442
   macro avg       0.81      0.80      0.80      1442
weighted avg       0.82      0.82      0.82      1442



In [611]:
kneighbors_class = LogisticRegression(C=0.6, class_weight='balanced')
kneighbors_class.fit(tfidf_X, y)
kneighbors_preds = kneighbors_class.predict(tfidf_X_test)

print(classification_report(y_test, kneighbors_preds))

              precision    recall  f1-score   support

         0.0       0.89      0.86      0.87       949
         1.0       0.74      0.79      0.77       493

    accuracy                           0.83      1442
   macro avg       0.81      0.82      0.82      1442
weighted avg       0.84      0.83      0.84      1442



## *Задание 4 (2 балла)

Для классификаторов LogisticRegression и Random Forest найдите способ извлечь важность признаков для предсказания токсичного класса. Сопоставьте полученные числа со словами (или нграммами) в словаре и найдите топ - 5 "токсичных" слов для каждого из классификаторов. 

Важное требование: в топе не должно быть стоп-слов. Для этого вам нужно будет правильным образом настроить векторизацию.

In [626]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from nltk.corpus import stopwords
import re
russian_stopwords = stopwords.words('russian')

In [627]:
def razdel_tokenize(text):
    tokens = list(tokenize(text))
    return [_.text for _ in tokens if _.text not in russian_stopwords]

In [628]:
data = pd.read_csv('labeled.csv')
data.toxic.value_counts(normalize=True)

toxic
0.0    0.66514
1.0    0.33486
Name: proportion, dtype: float64

In [644]:
vectorizer = TfidfVectorizer(min_df=10, max_df=0.3, tokenizer=razdel_tokenize, stop_words=list(russian_stopwords))

In [645]:
train, test = train_test_split(data, test_size=0.1, shuffle=True)
train.reset_index(inplace=True)
test.reset_index(inplace=True)

In [646]:
X = vectorizer.fit_transform(train.comment)
X_test = vectorizer.transform(test.comment)

C:\Users\robst\PycharmProjects\HSE_NLP\venv\Lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [647]:
X.shape, X_test.shape

((12970, 3326), (1442, 3326))

In [648]:
y = train.toxic.values
y_test = test.toxic.values

In [649]:
lr = LogisticRegression(C=0.1, class_weight='balanced')
lr.fit(X, y)
lr_preds = lr.predict(X_test)

rf = RandomForestClassifier(n_estimators=100, max_depth=20, )
rf.fit(X, y)
rf_preds = rf.predict(X_test)

In [650]:
# важность признаков
lr_feature_importance = lr.coef_[0]
rf_feature_importance = rf.feature_importances_

In [651]:
vec_feature_names = vectorizer.get_feature_names_out()

In [652]:
features = list(zip(feature_names, lr_feature_importance))
features = [f for f in features if re.match(r'^\w+$', f[0])]
features.sort(key=lambda f: f[1], reverse=True)
top_features = features[:5]
print("Топ-5 токсичных слов для LogisticRegression:", top_features)

Топ-5 токсичных слов для LogisticRegression: [('и', 1.453326773639802), ('он', 0.9132115723166851), ('не', 0.36685673132531216), ('только', 0.3066976697540769), ('ты', -0.019159634315481476)]


In [653]:
features = list(zip(feature_names, rf_feature_importance))
features = [f for f in features if re.match(r'^\w+$', f[0])]
features.sort(key=lambda f: f[1], reverse=True)
top_features = features[:5]
print("Топ-5 токсичных слов для RandomForest:", top_features)

Топ-5 токсичных слов для RandomForest: [('я', 0.030280603265437196), ('и', 0.027138146677595936), ('он', 0.006452118052484521), ('не', 0.001360665914755567), ('только', 0.00040460511266806145)]


Без фильтрации

In [654]:
# топ-5
top_five_lr_features = [vec_feature_names[i] for i in lr_feature_importance.argsort()[::-1][:5]]
top_five_rf_features = [vec_feature_names[i] for i in rf_feature_importance.argsort()[::-1][:5]]

In [655]:
print("Топ-5 токсичных слов для LogisticRegression:", top_five_lr_features)

Топ-5 токсичных слов для LogisticRegression: ['тебе', 'хохлы', 'хохлов', '!', 'нахуй']


In [656]:
print("Топ-5 токсичных слов для RandomForest:", top_five_rf_features)

Топ-5 токсичных слов для RandomForest: [')', 'хохлы', '(', 'тебе', '!']
